name: Aggiorna Classifica Volley

on:
  schedule:
    # Esegue ogni ora tra le 10:00 UTC e le 21:00 UTC
    - cron: '0 10-21/1 * * *'
  workflow_dispatch: # Permette avvio manuale

permissions:
  contents: write

# VARIABILE D'AMBIENTE CHE RISOLVE IL WARNING DI NODE.JS 20
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      # Aggiornato alla v5
      - name: Imposta Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Installa Dipendenze
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Esegui lo Script
        run: python main.py

      - name: Salva e Pubblica
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Aggiornamento dati completo"
          file_pattern: "*.html"
